"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class low_state_lcmt(object):
    __slots__ = ["q", "dq", "ddq", "tau_est", "quaternion", "gyroscope", "accelerometer", "rpy", "wireless_remote", "tick", "mode_pr", "mode_machine"]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(29) ]
        self.dq = [ 0.0 for dim0 in range(29) ]
        self.ddq = [ 0.0 for dim0 in range(29) ]
        self.tau_est = [ 0.0 for dim0 in range(29) ]
        self.quaternion = [ 0.0 for dim0 in range(4) ]
        self.gyroscope = [ 0.0 for dim0 in range(3) ]
        self.accelerometer = [ 0.0 for dim0 in range(3) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.wireless_remote = ""
        self.tick = 0
        self.mode_pr = 0
        self.mode_machine = 0

    def encode(self):
        buf = BytesIO()
        buf.write(low_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>29f', *self.q[:29]))
        buf.write(struct.pack('>29f', *self.dq[:29]))
        buf.write(struct.pack('>29f', *self.ddq[:29]))
        buf.write(struct.pack('>29f', *self.tau_est[:29]))
        buf.write(struct.pack('>4f', *self.quaternion[:4]))
        buf.write(struct.pack('>3f', *self.gyroscope[:3]))
        buf.write(struct.pack('>3f', *self.accelerometer[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(bytearray(self.wireless_remote[:40]))
        buf.write(struct.pack(">qBB", self.tick, self.mode_pr, self.mode_machine))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != low_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return low_state_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = low_state_lcmt()
        self.q = struct.unpack('>29f', buf.read(116))
        self.dq = struct.unpack('>29f', buf.read(116))
        self.ddq = struct.unpack('>29f', buf.read(116))
        self.tau_est = struct.unpack('>29f', buf.read(116))
        self.quaternion = struct.unpack('>4f', buf.read(16))
        self.gyroscope = struct.unpack('>3f', buf.read(12))
        self.accelerometer = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.wireless_remote = buf.read(40)
        self.tick, self.mode_pr, self.mode_machine = struct.unpack(">qBB", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if low_state_lcmt in parents: return 0
        tmphash = (0xc3251a111843be0f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if low_state_lcmt._packed_fingerprint is None:
            low_state_lcmt._packed_fingerprint = struct.pack(">Q", low_state_lcmt._get_hash_recursive([]))
        return low_state_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

