"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class low_cmd_lcmt(object):
    __slots__ = ["q", "dq", "tau", "kp", "kd", "mode_machine", "mode_pr"]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(29) ]
        self.dq = [ 0.0 for dim0 in range(29) ]
        self.tau = [ 0.0 for dim0 in range(29) ]
        self.kp = [ 0.0 for dim0 in range(29) ]
        self.kd = [ 0.0 for dim0 in range(29) ]
        self.mode_machine = 0
        self.mode_pr = 0

    def encode(self):
        buf = BytesIO()
        buf.write(low_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>29f', *self.q[:29]))
        buf.write(struct.pack('>29f', *self.dq[:29]))
        buf.write(struct.pack('>29f', *self.tau[:29]))
        buf.write(struct.pack('>29f', *self.kp[:29]))
        buf.write(struct.pack('>29f', *self.kd[:29]))
        buf.write(struct.pack(">BB", self.mode_machine, self.mode_pr))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != low_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return low_cmd_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = low_cmd_lcmt()
        self.q = struct.unpack('>29f', buf.read(116))
        self.dq = struct.unpack('>29f', buf.read(116))
        self.tau = struct.unpack('>29f', buf.read(116))
        self.kp = struct.unpack('>29f', buf.read(116))
        self.kd = struct.unpack('>29f', buf.read(116))
        self.mode_machine, self.mode_pr = struct.unpack(">BB", buf.read(2))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if low_cmd_lcmt in parents: return 0
        tmphash = (0x1a463aa044d6b0c4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if low_cmd_lcmt._packed_fingerprint is None:
            low_cmd_lcmt._packed_fingerprint = struct.pack(">Q", low_cmd_lcmt._get_hash_recursive([]))
        return low_cmd_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

