"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sport_state_lcmt(object):
    __slots__ = ["error_code", "mode", "progress", "gait_type", "foot_raise_height", "position", "body_height", "velocity", "yaw_speed"]

    def __init__(self):
        self.error_code = 0
        self.mode = 0
        self.progress = 0.0
        self.gait_type = 0
        self.foot_raise_height = 0.0
        self.position = [ 0.0 for dim0 in range(3) ]
        self.body_height = 0.0
        self.velocity = [ 0.0 for dim0 in range(3) ]
        self.yaw_speed = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(sport_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qBfBf", self.error_code, self.mode, self.progress, self.gait_type, self.foot_raise_height))
        buf.write(struct.pack('>3f', *self.position[:3]))
        buf.write(struct.pack(">f", self.body_height))
        buf.write(struct.pack('>3f', *self.velocity[:3]))
        buf.write(struct.pack(">f", self.yaw_speed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sport_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sport_state_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sport_state_lcmt()
        self.error_code, self.mode, self.progress, self.gait_type, self.foot_raise_height = struct.unpack(">qBfBf", buf.read(18))
        self.position = struct.unpack('>3f', buf.read(12))
        self.body_height = struct.unpack(">f", buf.read(4))[0]
        self.velocity = struct.unpack('>3f', buf.read(12))
        self.yaw_speed = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sport_state_lcmt in parents: return 0
        tmphash = (0x7dcd48c9dca0fd87) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sport_state_lcmt._packed_fingerprint is None:
            sport_state_lcmt._packed_fingerprint = struct.pack(">Q", sport_state_lcmt._get_hash_recursive([]))
        return sport_state_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)